"""empty message

Revision ID: 560658dae601
Revises: 6fc3089b6fec
Create Date: 2020-07-28 08:38:36.981705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560658dae601'
down_revision = '6fc3089b6fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugReport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bugReport')
    # ### end Alembic commands ###
